config/routes.rb
Rails.application.routes.draw do
  root 'wizards#index'

  devise_for :users

  resources :wizards, only: [:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/wizard.rb
class Wizard < ApplicationRecord


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/wizards_controller.rb
class WizardsController < ApplicationController
  def index
    @wizards = Wizard.all

    # render :index
  end

  def show
    @wizard = Wizard.find(params[:id])
    # render :show
  end
end

app/views/homes/index.html.erb
<p>
  Modify me in `app/views/homes/index.html.erb` or change the root directive in
  `config/routes.rb`
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WyzardsFerLyfe</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag 'application', media: 'all' %>
  
    <%= javascript_include_tag "vendor/modernizr" %>
  
  <%= csrf_meta_tags %>
</head>
<body>
  
  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">WyzardsFerLyfe</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <%- if current_user -%>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>
  
  <%- if Rails.env.development? || Rails.env.test? -%> 
    <%= javascript_tag do %>
      window.railsEnv = '<%= Rails.env %>'
    <%- end -%>
  <%- end -%>
  <%= javascript_pack_tag 'application' %>
  
  <%= yield :extra_footer %>
</body>
</html>

app/views/wizards/index.html.erb
<h1>THE GREAT LIST OF WIZARDS</h1>

<% @wizards.each do |wizard| %>
<li>
 <%= link_to wizard.name, wizard_path(wizard) %> | <%= wizard.age %> | <%= wizard.magic %>
</li>
<% end %>

app/views/wizards/show.html.erb
<h1>Wizard Show</h1>

<%= @wizard.name %>
<%= @wizard.age %>
<%= @wizard.magic %>